"""Dataset facts the design relies on, written to docs/eda.md.

    python -m src.common.eda
"""
import re
from collections import Counter

import pandas as pd
from unidecode import unidecode

from .io_utils import ROOT, data_is_synthetic, load_ground_truth, load_sources

TOKEN = re.compile(r"[a-z0-9]+")


def tokens(text):
    return TOKEN.findall(unidecode(text).lower())


def md_table(df):
    """Plain markdown table without the tabulate dependency."""
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    lines += ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join(lines)


def top_tokens(series, n=40):
    c = Counter(t for s in series for t in tokens(s))
    return ", ".join(f"{t} ({k})" for t, k in c.most_common(n))


def main():
    train, test = load_sources("train"), load_sources("test")
    gt = load_ground_truth()
    out = ["# EDA", "", "Generated by `python -m src.common.eda` from `data/raw/dataset`.", ""]
    if data_is_synthetic():
        out += ["**Synthetic stand-in data** (scripts/make_synthetic_data.py; see docs/problems.md). "
                "Rerun this module once the organiser files are in place.", ""]

    rows = []
    for split, src in (("train", train), ("test", test)):
        for s, df in src.items():
            for country, k in df["country"].value_counts().sort_index().items():
                rows.append((split, s, country, k))
    counts = pd.DataFrame(rows, columns=["split", "source", "country", "records"])
    out += ["## Records per split, source and country", "", md_table(counts), ""]

    s1 = train["source1"].set_index("entity_id")
    per = pd.DataFrame({"s1_id": list(gt), "n": [len(v) for v in gt.values()],
                        "n_s2": [sum(m.startswith("S2-") for m in v) for v in gt.values()],
                        "n_s3": [sum(m.startswith("S3-") for m in v) for v in gt.values()]})
    per["country"] = per["s1_id"].map(s1["country"])
    hist = per.groupby(["country", "n"]).size().unstack(fill_value=0)
    out += ["## Matches per S1 entity (train)", "",
            f"- singletons: {(per.n == 0).mean():.3f} of S1 entities "
            f"({(per.n == 0).sum()} of {len(per)})",
            f"- mean matches per S1: {per.n.mean():.2f} (S2 {per.n_s2.mean():.2f}, S3 {per.n_s3.mean():.2f})",
            f"- max matches per S1: {per.n.max()}", "",
            md_table(hist.reset_index()), ""]
    for col in ("n_s2", "n_s3"):
        h = per[col].value_counts().sort_index()
        out += [f"- {col} histogram: " + ", ".join(f"{k}: {v}" for k, v in h.items())]
    matched = [m for v in gt.values() for m in v]
    other = pd.concat([train["source2"], train["source3"]])
    out += ["", f"- S2/S3 records matched to some S1: {len(set(matched))} of {len(other)} "
            f"({len(set(matched)) / len(other):.3f}); records matched to two S1 entities: "
            f"{sum(1 for k in Counter(matched).values() if k > 1)}", ""]

    out += ["## Top 40 tokens per country (train, all sources)", ""]
    allrec = pd.concat(list(train.values()))
    for country, g in allrec.groupby("country"):
        out += [f"### {country}", "", "- name: " + top_tokens(g["business_name"]),
                "- address: " + top_tokens(g["business_address"]), ""]
    testrec = pd.concat(list(test.values()))
    for country in sorted(set(testrec.country) - set(allrec.country)):
        g = testrec[testrec.country == country]
        out += [f"### {country} (test only)", "", "- name: " + top_tokens(g["business_name"]),
                "- address: " + top_tokens(g["business_address"]), ""]

    out += ["## Variant examples (S1 name -> matched name / address)", ""]
    lookup = pd.concat([train["source2"], train["source3"]]).set_index("entity_id")
    shown = 0
    for sid, ms in gt.items():
        if not ms or shown >= 12:
            continue
        m = lookup.loc[ms[0]]
        if m.business_name.lower() != s1.loc[sid].business_name.lower():
            out.append(f"- `{s1.loc[sid].business_name}` -> `{m.business_name}`; "
                       f"`{s1.loc[sid].business_address}` -> `{m.business_address}`")
            shown += 1
    (ROOT / "docs" / "eda.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("wrote docs/eda.md")


if __name__ == "__main__":
    main()
